version: '3'
services:
  elasticsearch:
    image: infovip/infovip-es
    container_name: es
    environment:
      - "XMS=1g"
      - "XMX=1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - ivip
  web:
    image: infovip/infovip-web
    container_name: web
    ports:
      - 8443:8443
      - 9990:9990
    networks:
      - ivip
    volumes:
      - ../../infovip-ear:/opt/deploy
  db:
    image: infovip/infovip-db
    container_name: db 
    ports:
      - 5432:5432
    networks:
      - ivip
  
networks:
  ivip:
    driver: bridge
